name = "Auralith"
author = "AmeliaCute"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1e1b325fb53240bc48e9d5dbf6664b61fdd27a4593222091a0f2baffeeef894"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
