["Common settings"]
	#List of additional item registry keys allowed to break logs
	allowed_items = [
		"minecraft:flint", 
		"rocks:cobblestone_splitter",
		"rocks:granite_splitter",
		"rocks:diorite_splitter",
		"rocks:andesite_splitter",
		"rocks:sandstone_splitter",
		"rocks:red_sandstone_splitter",
		"rocks:cobblestone_splitter",      
	]
